var Utils,i,km,sks;Backbone.View.prototype.close=function(){this.remove();this.unbind();return typeof this.onClose==="function"?this.onClose():void 0;};
(function(a){a.fn.scrollTo=function(b,f){var c;if(b==null){b=250;}try{a("html, body").animate({scrollTop:a(this).offset().top+"px"},b,null,f);}catch(d){c=d;
console.log(c);console.log("Scroll error with 'this'");console.log(this);}return this;};a.fn.topCenter=function(){this.css("position","absolute");this.css("top",a(window).scrollTop()+"px");
return this.css("left",((a(window).width()-this.outerWidth())/2)+a(window).scrollLeft()+"px");};return a.fn.middleCenter=function(){this.css("position","absolute");
this.css("top",((a(window).height()-this.outerHeight())/2)+a(window).scrollTop()+"px");return this.css("left",((a(window).width()-this.outerWidth())/2)+a(window).scrollLeft()+"px");
};})(jQuery);$.ajaxSetup({statusCode:{404:function(f,b,d){var c,a,e;c=f.status;e=f.statusText;a=~f.responseText.indexOf("unauthorized");if(a){Utils.midAlert("Session closed<br>Please log in and try again.");
return Tangerine.user.logout();}}}});km={"0":48,"1":49,"2":50,"3":51,"4":52,"5":53,"6":54,"7":55,"8":56,"9":57,a:65,b:66,c:67,d:68,e:69,f:70,g:71,h:72,i:73,j:74,k:75,l:76,m:77,n:78,o:79,p:80,q:81,r:82,s:83,t:84,u:85,v:86,w:87,x:88,y:89,z:90};
sks=[{q:(function(){var b,a;a=[];for(i=b=0;b<=6;i=++b){a.push(km["0100ser"[i]]);}return a;})(),i:0,c:function(){var a;a=new Settings({_id:"TangerineSettings"});
return a.fetch({success:function(b){b.set({context:"server"});b.save();return Tangerine.router.navigate("",true);}});}},{q:(function(){var b,a;a=[];for(i=b=0;
b<=6;i=++b){a.push(km["0100mob"[i]]);}return a;})(),i:0,c:function(){var a;a=new Settings({_id:"TangerineSettings"});return a.fetch({success:function(b){b.set({context:"mobile"});
b.save();return Tangerine.router.navigate("",true);}});}},{q:(function(){var b,a;a=[];for(i=b=0;b<=6;i=++b){a.push(km["0100cla"[i]]);}return a;})(),i:0,c:function(){var a;
a=new Settings({_id:"TangerineSettings"});return a.fetch({success:function(b){b.set({context:"class"});b.save();return Tangerine.router.navigate("",true);
}});}}];$(document).keydown(function(g){var d,c,f,b,a;a=[];for(d=f=0,b=sks.length;f<b;d=++f){c=sks[d];a.push(g.keyCode===sks[d].q[sks[d].i++]?sks[d].i===sks[d].q.length?sks[d]["c"]():void 0:sks[d].i=0);
}return a;});String.prototype.safetyDance=function(){return this.replace(/\s/g,"_").replace(/[^a-zA-Z0-9_]/g,"");};Math.ave=function(){var b,a,d,c;b=0;
for(d=0,c=arguments.length;d<c;d++){a=arguments[d];b+=a;}b/=arguments.length;return b;};Math.isInt=function(){return typeof n==="number"&&parseFloat(n)===parseInt(n,10)&&!isNaN(n);
};Math.decimals=function(c,b){var a;a=Math.pow(10,b);c*=a;c=c+(c<(typeof 0==="function"?0(-{0.5:+0.5}):void 0))>>0;return c/=a;};Utils=(function(){function a(){}a.confirm=function(c,b){var d;
if(((d=navigator.notification)!=null?d.confirm:void 0)!=null){navigator.notification.confirm(c,function(e){if(e===1){return b.callback(true);}else{if(e===2){return b.callback(false);
}else{return b.callback(e);}}},b.title,b.action+",Cancel");}else{if(window.confirm(c)){b.callback(true);return true;}else{b.callback(false);return false;
}}return 0;};a.getValues=function(b){var c;c={};$(b).find("input, textarea").each(function(d,e){return c[e.id]=e.value;});return c;};a.cleanURL=function(b){if((typeof b.indexOf==="function"?b.indexOf("%"):void 0)!==-1){return b=decodeURIComponent(b);
}else{return b;}};a.importAssessmentFromIris=function(c){var b;b={filter:"tangerine/downloadFilter",create_target:true,query_params:{dKey:c}};return $.couch.replicate(Tangerine.iris.host+"/tangerine","tangerine",{success:function(e,d){return console.log([" success",e,d]);
}},b);};a.topAlert=function(b){return $("<div class='disposable_alert'>"+b+"</div>").appendTo("#content").topCenter().delay(2000).fadeOut(250,function(){return $(this).remove();
});};a.midAlert=function(b){return $("<div class='disposable_alert'>"+b+"</div>").appendTo("#content").middleCenter().delay(2000).fadeOut(250,function(){return $(this).remove();
});};a.S4=function(){return(((1+Math.random())*65536)|0).toString(16).substring(1);};a.guid=function(){return this.S4()+this.S4()+"-"+this.S4()+"-"+this.S4()+"-"+this.S4()+"-"+this.S4()+this.S4()+this.S4();
};a.flash=function(b){if(b==null){b="red";}$("body").css({backgroundColor:b});return setTimeout(function(){return $("body").css({backgroundColor:"white"});
},1000);};a.$_GET=function(c,b){var e,d;d={};e=window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi,function(f,g,h){h=~h.indexOf("#")?h.split("#")[0]:h;
return d[g]=h.split("#")[0];});return d;};a.resizeScrollPane=function(){return $(".scroll_pane").height($(window).height()-($("#navigation").height()+$("#footer").height()+100));
};return a;})();$(function(){$("#content").on("click",".clear_message",null,function(b){return $(b.target).parent().fadeOut(250,function(){return $(this).empty().show();
});});$("#content").on("click",".parent_remove",null,function(b){return $(b.target).parent().fadeOut(250,function(){return $(this).remove();});});$("#content").on("click",".alert_button",function(){var a;
a=$(this).attr("data-alert")?$(this).attr("data-alert"):$(this).val();return Utils.disposableAlert(a);});return $("#content").on("click",".disposable_alert",function(){return $(this).stop().fadeOut(100,function(){return $(this).remove();
});});});